name: Detect SQL Changes
on:
  pull_request:
    branches:
      - main
    paths:
      - sql/**/*.sql

jobs:
  check_sql:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # accede a commits anteriores

      - name: Get changed SQL files
        id: changed_files
        run: |
          echo "Changes in SQL..."
          echo "FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep '\.sql$' || echo '')" >> $GITHUB_ENV

      - name: Run SQL table extraction
        if: env.FILES != ''
        run: python scripts/extract_tables.py $FILES

      - name: Add and commit detected_tables.txt file
        if: env.FILES != ''
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout ${{ github.head_ref }} 
          git add scripts/detected_tables.txt
          git commit -m "Actualizar detected_tables.txt desde GitHub Actions"
          git push origin ${{ github.head_ref }}