name: Detect SQL Changes
on:
  push:
    branches:
      - main
    paths:
      - sql/**/*.sql
  pull_request:
    branches:
      - rama2
    paths:
      - sql/**/*.sql
jobs:
  check_sql:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Get changed SQL files
        id: changed_files
        run: >
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep '\.sql$' | tr '\n' ' ')" >> $GITHUB_ENV
          else
            echo "FILES=$(git diff --name-only HEAD~1 ${{ github.sha }} | grep '\.sql$' | tr '\n' ' ')" >> $GITHUB_ENV
          fi
      - name: Run SQL table extraction
        if: env.FILES != ''
        run: python scripts/extract_tables.py $FILES