name: Detect SQL Changes
on:
  push:
    branches:
      - main
    paths:
      - sql/**/*.sql
  pull_request:
    branches:
      - rama2
    paths:
      - sql/**/*.sql
jobs:
  check_sql:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Permite acceder a HEAD~1
      - name: Get changed SQL files
        id: changed_files
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            BASE_COMMIT=${{ github.event.pull_request.base.sha }}
          else
            BASE_COMMIT=${{ github.event.before }}
          fi

          if [ -z "$BASE_COMMIT" ]; then
            echo "No previous commit found, skipping diff."
            echo "FILES=" >> $GITHUB_ENV
          else
            echo "FILES=$(git diff --name-only $BASE_COMMIT ${{ github.sha }} | grep '\.sql$' | tr '\n' ' ')" >> $GITHUB_ENV
          fi
      - name: Run SQL table extraction
        if: env.FILES != ''
        run: python scripts/extract_tables.py $FILES
      - name: List scripts directory
        run: ls -R scripts
      - name: Check temp file
        run: cat /tmp/detected_tables.txt
