name: Detect SQL Changes
on:
  push:
    branches:
      - '**'  # Se ejecuta en cualquier push
    paths:
      - sql/**/*.sql

jobs:
  check_sql:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Permite acceder a commits anteriores

      - name: Get changed SQL files
        id: changed_files
        run: |
          echo "Detectando cambios en archivos SQL..."
          echo "FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep '\.sql$' || echo '')" >> $GITHUB_ENV

      - name: Run SQL table extraction
        if: env.FILES != ''
        run: python scripts/extract_tables.py $FILES

      - name: List scripts directory
        run: ls -R scripts

      - name: Agregar y commitear detected_tables.txt
        if: env.FILES != ''
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout ${{ github.head_ref }} 
          git add scripts/detected_tables.txt
          git commit -m "Actualizar detected_tables.txt desde GitHub Actions"
          git push origin ${{ github.head_ref }}

      - name: Crear PR autom치tico
        if: env.FILES != ''
        uses: peter-evans/create-pull-request@v5
        with:
          base: main
          branch: ${{ github.head_ref }} # Usar la rama actual
          title: "Actualizaci칩n autom치tica de detected_tables.txt"
          body: "Este PR fue creado autom치ticamente para actualizar detected_tables.txt basado en cambios en archivos SQL."
          draft: false # Asegura que el PR se cree directamente y no como borrador